{
  imports = [
    ./hyprland/default.nix
    ./programs/fastfetch/fastfetch.nix
    ./programs/kitty.nix
    ./programs/swaync.nix
    ./programs/yazi/yazi.nix
    ./programs/btop.nix
    ./programs/zsh.nix
    ./programs/feh.nix
    ./programs/cava.nix
    ./programs/zathura.nix
    ./programs/rofi/rofi.nix
    ./programs/spicetify.nix
    ./programs/coding-pkgs.nix
    ./programs/themes
    ./programs/waybar
  ];
}
