{
  imports = [
    ./hyprland/default.nix
    ./programs/fastfetch
    ./programs/wezterm
    ./programs/swaync
    ./programs/btop
    ./programs/zsh
    ./programs/starship
    ./programs/feh
    ./programs/cava
    ./programs/zathura
    ./programs/rofi
    ./programs/themes
    ./programs/waybar
    ./programs/lazygit
    ./programs/coding
  ];
}
