{
  imports = [
    ./niri.nix
    ./portals.nix
    ./user.nix
    ./docker.nix
    ./xserver.nix
    ./pipewire.nix
    ./bluetooth.nix
    ./power-profile.nix
    ./bootloader.nix
    ./virt-manager.nix
    ./udisk.nix
    ./opentablet.nix
    ./sddm.nix
    ./polkit.nix
    ./kdeconnect.nix
    ./flatpak.nix
  ];
}
